---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/actions/virtual-environments
name: Deploy
on:
  push:
    branches:
      - "master"
defaults:
  run:
    shell: bash
concurrency: ${{ github.workflow }}
jobs:
  build:
    name: Build
    if: github.repository == 'supercaracal/dummy-web-server'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up ko
        uses: ko-build/setup-ko@v0.7

      - name: Log into GitHub Container Registry
        run: >
          echo "${{ secrets.GITHUB_TOKEN }}"
          | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push an image to GitHub Container Registry
        env:
          KO_DOCKER_REPO: "ghcr.io/${{ github.repository }}"
        run: ko build --tags latest --bare .
